title: Mia's Music Studio
description: The best age to start learning is from 2-100, says Lang Lang. Lang Lang began learning the piano at age 3.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
